FROM ubuntu:20.04

WORKDIR /

ENV DEBIAN_FRONTEND=noninteractive
ENV LIBGUESTFS_DEBUG=1
ENV LIBGUESTFS_TRACE=1

RUN apt-get update

RUN apt-get install -y --no-install-recommends tzdata
RUN apt-get install -y qemu-kvm libguestfs-tools libvirt-daemon-system 

COPY hack/local-test-env.sh /local-test-env.sh

ENTRYPOINT /local-test-env.sh
